# Site settings
title: maxidev
author: Maxi Dev
baseurl: "" # Empty for user/organization pages (e.g., username.github.io)
url: "https://maxidev.github.io" # Your GitHub Pages URL

# Remote Theme
remote_theme: "jekyll/minima@1e8a445"

# Plugins (required for remote theme)
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: pretty
